// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: api/protobuf-spec/ofc_app/ofc_com_app.proto

package ofc_app

import (
	context "context"
	reflect "reflect"
	sync "sync"

	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/mwitkow/go-proto-validators"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//添加应用
type AppRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid    int64  `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Appkey string `protobuf:"bytes,2,opt,name=appkey,proto3" json:"appkey,omitempty"`
	// @inject_tag: v:"required#应用名不能为空"
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty" v:"required#应用名不能为空"`
	// @inject_tag: v:"required#行业类型不能为空"
	IndustryType string `protobuf:"bytes,4,opt,name=industry_type,json=industryType,proto3" json:"industry_type,omitempty" v:"required#行业类型不能为空"`
	Info         string `protobuf:"bytes,5,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *AppRequest) Reset() {
	*x = AppRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppRequest) ProtoMessage() {}

func (x *AppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppRequest.ProtoReflect.Descriptor instead.
func (*AppRequest) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_ofc_app_ofc_com_app_proto_rawDescGZIP(), []int{0}
}

func (x *AppRequest) GetCid() int64 {
	if x != nil {
		return x.Cid
	}
	return 0
}

func (x *AppRequest) GetAppkey() string {
	if x != nil {
		return x.Appkey
	}
	return ""
}

func (x *AppRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppRequest) GetIndustryType() string {
	if x != nil {
		return x.IndustryType
	}
	return ""
}

func (x *AppRequest) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

//添加应用返回
type AppReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Appkey string `protobuf:"bytes,1,opt,name=appkey,proto3" json:"appkey,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *AppReply) Reset() {
	*x = AppReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppReply) ProtoMessage() {}

func (x *AppReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppReply.ProtoReflect.Descriptor instead.
func (*AppReply) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_ofc_app_ofc_com_app_proto_rawDescGZIP(), []int{1}
}

func (x *AppReply) GetAppkey() string {
	if x != nil {
		return x.Appkey
	}
	return ""
}

func (x *AppReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

//获取app
type AppGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Appkey string `protobuf:"bytes,1,opt,name=appkey,proto3" json:"appkey,omitempty"`
	Cid    int64  `protobuf:"varint,2,opt,name=cid,proto3" json:"cid,omitempty" v:"required#参数cid必须"`
	Page   int64  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *AppGetRequest) Reset() {
	*x = AppGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppGetRequest) ProtoMessage() {}

func (x *AppGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppGetRequest.ProtoReflect.Descriptor instead.
func (*AppGetRequest) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_ofc_app_ofc_com_app_proto_rawDescGZIP(), []int{2}
}

func (x *AppGetRequest) GetAppkey() string {
	if x != nil {
		return x.Appkey
	}
	return ""
}

func (x *AppGetRequest) GetCid() int64 {
	if x != nil {
		return x.Cid
	}
	return 0
}

func (x *AppGetRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

//单个app信息返回
type AppOneReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId        int64  `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Appkey       string `protobuf:"bytes,2,opt,name=appkey,proto3" json:"appkey,omitempty"`
	Name         string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	IndustryType string `protobuf:"bytes,4,opt,name=industry_type,json=industryType,proto3" json:"industry_type,omitempty"`
	Secret       string `protobuf:"bytes,5,opt,name=secret,proto3" json:"secret,omitempty"`
	Info         string `protobuf:"bytes,6,opt,name=info,proto3" json:"info,omitempty"`
	Cid          int64  `protobuf:"varint,7,opt,name=cid,proto3" json:"cid,omitempty"`
}

func (x *AppOneReply) Reset() {
	*x = AppOneReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppOneReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppOneReply) ProtoMessage() {}

func (x *AppOneReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppOneReply.ProtoReflect.Descriptor instead.
func (*AppOneReply) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_ofc_app_ofc_com_app_proto_rawDescGZIP(), []int{3}
}

func (x *AppOneReply) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *AppOneReply) GetAppkey() string {
	if x != nil {
		return x.Appkey
	}
	return ""
}

func (x *AppOneReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppOneReply) GetIndustryType() string {
	if x != nil {
		return x.IndustryType
	}
	return ""
}

func (x *AppOneReply) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *AppOneReply) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *AppOneReply) GetCid() int64 {
	if x != nil {
		return x.Cid
	}
	return 0
}

//app列表返回
type AppListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List     []*AppOneReply `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	Paginate *Page          `protobuf:"bytes,2,opt,name=Paginate,proto3" json:"Paginate,omitempty"`
}

func (x *AppListReply) Reset() {
	*x = AppListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppListReply) ProtoMessage() {}

func (x *AppListReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppListReply.ProtoReflect.Descriptor instead.
func (*AppListReply) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_ofc_app_ofc_com_app_proto_rawDescGZIP(), []int{4}
}

func (x *AppListReply) GetList() []*AppOneReply {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *AppListReply) GetPaginate() *Page {
	if x != nil {
		return x.Paginate
	}
	return nil
}

//修改app相关配置
type AppKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: v:"required#appkey必须"
	Appkey string `protobuf:"bytes,1,opt,name=appkey,proto3" json:"appkey,omitempty" v:"required#appkey必须"`
}

func (x *AppKeyRequest) Reset() {
	*x = AppKeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppKeyRequest) ProtoMessage() {}

func (x *AppKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppKeyRequest.ProtoReflect.Descriptor instead.
func (*AppKeyRequest) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_ofc_app_ofc_com_app_proto_rawDescGZIP(), []int{5}
}

func (x *AppKeyRequest) GetAppkey() string {
	if x != nil {
		return x.Appkey
	}
	return ""
}

//刷新密钥返回
type SecretSaveReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Secret string `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
}

func (x *SecretSaveReply) Reset() {
	*x = SecretSaveReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecretSaveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretSaveReply) ProtoMessage() {}

func (x *SecretSaveReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretSaveReply.ProtoReflect.Descriptor instead.
func (*SecretSaveReply) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_ofc_app_ofc_com_app_proto_rawDescGZIP(), []int{6}
}

func (x *SecretSaveReply) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

//消息抄送
type MessageUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: v:"required#appkey必须"
	Appkey string `protobuf:"bytes,1,opt,name=appkey,proto3" json:"appkey,omitempty" v:"required#appkey必须"`
	// @inject_tag: v:"required#抄送地址必须"
	MessageUrl string `protobuf:"bytes,2,opt,name=message_url,json=messageUrl,proto3" json:"message_url,omitempty" v:"required#抄送地址必须"`
}

func (x *MessageUrlRequest) Reset() {
	*x = MessageUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageUrlRequest) ProtoMessage() {}

func (x *MessageUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageUrlRequest.ProtoReflect.Descriptor instead.
func (*MessageUrlRequest) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_ofc_app_ofc_com_app_proto_rawDescGZIP(), []int{7}
}

func (x *MessageUrlRequest) GetAppkey() string {
	if x != nil {
		return x.Appkey
	}
	return ""
}

func (x *MessageUrlRequest) GetMessageUrl() string {
	if x != nil {
		return x.MessageUrl
	}
	return ""
}

//标识管理
type IdentifierRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: v:"required#appkey必须"
	Appkey              string `protobuf:"bytes,1,opt,name=appkey,proto3" json:"appkey,omitempty" v:"required#appkey必须"`
	IosBundleIdentifier string `protobuf:"bytes,2,opt,name=ios_bundle_identifier,json=iosBundleIdentifier,proto3" json:"ios_bundle_identifier,omitempty"`
	AndroidPackageName  string `protobuf:"bytes,3,opt,name=android_package_name,json=androidPackageName,proto3" json:"android_package_name,omitempty"`
}

func (x *IdentifierRequest) Reset() {
	*x = IdentifierRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdentifierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentifierRequest) ProtoMessage() {}

func (x *IdentifierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentifierRequest.ProtoReflect.Descriptor instead.
func (*IdentifierRequest) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_ofc_app_ofc_com_app_proto_rawDescGZIP(), []int{8}
}

func (x *IdentifierRequest) GetAppkey() string {
	if x != nil {
		return x.Appkey
	}
	return ""
}

func (x *IdentifierRequest) GetIosBundleIdentifier() string {
	if x != nil {
		return x.IosBundleIdentifier
	}
	return ""
}

func (x *IdentifierRequest) GetAndroidPackageName() string {
	if x != nil {
		return x.AndroidPackageName
	}
	return ""
}

//文案添加修改请求
type CopywritingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: v:"required#appkey必须"
	Appkey string `protobuf:"bytes,1,opt,name=appkey,proto3" json:"appkey,omitempty" v:"required#appkey必须"`
	// @inject_tag: v:"required#文案类型必须"
	CustomType string `protobuf:"bytes,2,opt,name=custom_type,json=customType,proto3" json:"custom_type,omitempty" v:"required#文案类型必须"`
	// @inject_tag: v:"required#文案内容必须"
	CustomCopywriting string `protobuf:"bytes,3,opt,name=custom_copywriting,json=customCopywriting,proto3" json:"custom_copywriting,omitempty" v:"required#文案内容必须"`
	CopywritingId     int64  `protobuf:"varint,4,opt,name=copywriting_id,json=copywritingId,proto3" json:"copywriting_id,omitempty"`
}

func (x *CopywritingRequest) Reset() {
	*x = CopywritingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CopywritingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopywritingRequest) ProtoMessage() {}

func (x *CopywritingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopywritingRequest.ProtoReflect.Descriptor instead.
func (*CopywritingRequest) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_ofc_app_ofc_com_app_proto_rawDescGZIP(), []int{9}
}

func (x *CopywritingRequest) GetAppkey() string {
	if x != nil {
		return x.Appkey
	}
	return ""
}

func (x *CopywritingRequest) GetCustomType() string {
	if x != nil {
		return x.CustomType
	}
	return ""
}

func (x *CopywritingRequest) GetCustomCopywriting() string {
	if x != nil {
		return x.CustomCopywriting
	}
	return ""
}

func (x *CopywritingRequest) GetCopywritingId() int64 {
	if x != nil {
		return x.CopywritingId
	}
	return 0
}

//获取文案
type CopywritingGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: v:"required#appkey必须"
	Appkey        string `protobuf:"bytes,1,opt,name=appkey,proto3" json:"appkey,omitempty" v:"required#appkey必须"`
	CopywritingId int64  `protobuf:"varint,2,opt,name=copywriting_id,json=copywritingId,proto3" json:"copywriting_id,omitempty"`
	Page          int64  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *CopywritingGetRequest) Reset() {
	*x = CopywritingGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CopywritingGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopywritingGetRequest) ProtoMessage() {}

func (x *CopywritingGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopywritingGetRequest.ProtoReflect.Descriptor instead.
func (*CopywritingGetRequest) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_ofc_app_ofc_com_app_proto_rawDescGZIP(), []int{10}
}

func (x *CopywritingGetRequest) GetAppkey() string {
	if x != nil {
		return x.Appkey
	}
	return ""
}

func (x *CopywritingGetRequest) GetCopywritingId() int64 {
	if x != nil {
		return x.CopywritingId
	}
	return 0
}

func (x *CopywritingGetRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

//单个文案返回
type CopywritingOneReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CopywritingId     int64  `protobuf:"varint,1,opt,name=copywriting_id,json=copywritingId,proto3" json:"copywriting_id,omitempty"`
	Appkey            string `protobuf:"bytes,2,opt,name=appkey,proto3" json:"appkey,omitempty"`
	CustomType        string `protobuf:"bytes,3,opt,name=custom_type,json=customType,proto3" json:"custom_type,omitempty"`
	CustomCopywriting string `protobuf:"bytes,4,opt,name=custom_copywriting,json=customCopywriting,proto3" json:"custom_copywriting,omitempty"`
}

func (x *CopywritingOneReply) Reset() {
	*x = CopywritingOneReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CopywritingOneReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopywritingOneReply) ProtoMessage() {}

func (x *CopywritingOneReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopywritingOneReply.ProtoReflect.Descriptor instead.
func (*CopywritingOneReply) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_ofc_app_ofc_com_app_proto_rawDescGZIP(), []int{11}
}

func (x *CopywritingOneReply) GetCopywritingId() int64 {
	if x != nil {
		return x.CopywritingId
	}
	return 0
}

func (x *CopywritingOneReply) GetAppkey() string {
	if x != nil {
		return x.Appkey
	}
	return ""
}

func (x *CopywritingOneReply) GetCustomType() string {
	if x != nil {
		return x.CustomType
	}
	return ""
}

func (x *CopywritingOneReply) GetCustomCopywriting() string {
	if x != nil {
		return x.CustomCopywriting
	}
	return ""
}

//文案列表
type CopywritingListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List     []*CopywritingOneReply `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	Paginate *Page                  `protobuf:"bytes,2,opt,name=Paginate,proto3" json:"Paginate,omitempty"`
}

func (x *CopywritingListReply) Reset() {
	*x = CopywritingListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CopywritingListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopywritingListReply) ProtoMessage() {}

func (x *CopywritingListReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopywritingListReply.ProtoReflect.Descriptor instead.
func (*CopywritingListReply) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_ofc_app_ofc_com_app_proto_rawDescGZIP(), []int{12}
}

func (x *CopywritingListReply) GetList() []*CopywritingOneReply {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *CopywritingListReply) GetPaginate() *Page {
	if x != nil {
		return x.Paginate
	}
	return nil
}

type Page struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PagetNo    int64 `protobuf:"varint,1,opt,name=PagetNo,proto3" json:"PagetNo,omitempty"`
	PageSize   int64 `protobuf:"varint,2,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	TotalPage  int64 `protobuf:"varint,3,opt,name=TotalPage,proto3" json:"TotalPage,omitempty"`
	TotalCount int64 `protobuf:"varint,4,opt,name=TotalCount,proto3" json:"TotalCount,omitempty"`
}

func (x *Page) Reset() {
	*x = Page{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_ofc_app_ofc_com_app_proto_rawDescGZIP(), []int{13}
}

func (x *Page) GetPagetNo() int64 {
	if x != nil {
		return x.PagetNo
	}
	return 0
}

func (x *Page) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *Page) GetTotalPage() int64 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

func (x *Page) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_api_protobuf_spec_ofc_app_ofc_com_app_proto protoreflect.FileDescriptor

var file_api_protobuf_spec_ofc_app_ofc_com_app_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2d, 0x73,
	0x70, 0x65, 0x63, 0x2f, 0x6f, 0x66, 0x63, 0x5f, 0x61, 0x70, 0x70, 0x2f, 0x6f, 0x66, 0x63, 0x5f,
	0x63, 0x6f, 0x6d, 0x5f, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6f,
	0x66, 0x63, 0x2e, 0x61, 0x70, 0x70, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6d, 0x77, 0x69, 0x74, 0x6b, 0x6f, 0x77, 0x2f, 0x67, 0x6f, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2d, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x2f, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x93, 0x01, 0x0a, 0x0a,
	0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x63, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x70, 0x70, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70,
	0x70, 0x6b, 0x65, 0x79, 0x12, 0x1a, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x06, 0xe2, 0xdf, 0x1f, 0x02, 0x58, 0x01, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x2b, 0x0a, 0x0d, 0x69, 0x6e, 0x64, 0x75, 0x73, 0x74, 0x72, 0x79, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x42, 0x06, 0xe2, 0xdf, 0x1f, 0x02, 0x58, 0x01, 0x52,
	0x0c, 0x69, 0x6e, 0x64, 0x75, 0x73, 0x74, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x66,
	0x6f, 0x22, 0x36, 0x0a, 0x08, 0x41, 0x70, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x70, 0x70, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61,
	0x70, 0x70, 0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x4d, 0x0a, 0x0d, 0x41, 0x70, 0x70,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x70,
	0x70, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x70, 0x6b,
	0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x63, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0xb3, 0x01, 0x0a, 0x0b, 0x41, 0x70, 0x70,
	0x4f, 0x6e, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x70, 0x70, 0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x69,
	0x6e, 0x64, 0x75, 0x73, 0x74, 0x72, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x69, 0x6e, 0x64, 0x75, 0x73, 0x74, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03,
	0x63, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x63, 0x69, 0x64, 0x22, 0x63,
	0x0a, 0x0c, 0x41, 0x70, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x28,
	0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6f,
	0x66, 0x63, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x41, 0x70, 0x70, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x52, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x69,
	0x6e, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6f, 0x66, 0x63,
	0x2e, 0x61, 0x70, 0x70, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x52, 0x08, 0x50, 0x61, 0x67, 0x69, 0x6e,
	0x61, 0x74, 0x65, 0x22, 0x2f, 0x0a, 0x0d, 0x41, 0x70, 0x70, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x42, 0x06, 0xe2, 0xdf, 0x1f, 0x02, 0x58, 0x01, 0x52, 0x06, 0x61, 0x70,
	0x70, 0x6b, 0x65, 0x79, 0x22, 0x29, 0x0a, 0x0f, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x53, 0x61,
	0x76, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x22,
	0x5c, 0x0a, 0x11, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x42, 0x06, 0xe2, 0xdf, 0x1f, 0x02, 0x58, 0x01, 0x52, 0x06, 0x61, 0x70,
	0x70, 0x6b, 0x65, 0x79, 0x12, 0x27, 0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f,
	0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x06, 0xe2, 0xdf, 0x1f, 0x02, 0x58,
	0x01, 0x52, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x22, 0x99, 0x01,
	0x0a, 0x11, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x06, 0xe2, 0xdf, 0x1f, 0x02, 0x58, 0x01, 0x52, 0x06, 0x61, 0x70, 0x70,
	0x6b, 0x65, 0x79, 0x12, 0x32, 0x0a, 0x15, 0x69, 0x6f, 0x73, 0x5f, 0x62, 0x75, 0x6e, 0x64, 0x6c,
	0x65, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x13, 0x69, 0x6f, 0x73, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x49, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x30, 0x0a, 0x14, 0x61, 0x6e, 0x64, 0x72, 0x6f,
	0x69, 0x64, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x61, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x50, 0x61,
	0x63, 0x6b, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xbb, 0x01, 0x0a, 0x12, 0x43, 0x6f,
	0x70, 0x79, 0x77, 0x72, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1e, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x06, 0xe2, 0xdf, 0x1f, 0x02, 0x58, 0x01, 0x52, 0x06, 0x61, 0x70, 0x70, 0x6b, 0x65, 0x79,
	0x12, 0x27, 0x0a, 0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x06, 0xe2, 0xdf, 0x1f, 0x02, 0x58, 0x01, 0x52, 0x0a, 0x63,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x35, 0x0a, 0x12, 0x63, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x5f, 0x63, 0x6f, 0x70, 0x79, 0x77, 0x72, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x06, 0xe2, 0xdf, 0x1f, 0x02, 0x58, 0x01, 0x52, 0x11, 0x63,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x43, 0x6f, 0x70, 0x79, 0x77, 0x72, 0x69, 0x74, 0x69, 0x6e, 0x67,
	0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x70, 0x79, 0x77, 0x72, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x5f,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x63, 0x6f, 0x70, 0x79, 0x77, 0x72,
	0x69, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x22, 0x72, 0x0a, 0x15, 0x43, 0x6f, 0x70, 0x79, 0x77,
	0x72, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1e, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x06, 0xe2, 0xdf, 0x1f, 0x02, 0x58, 0x01, 0x52, 0x06, 0x61, 0x70, 0x70, 0x6b, 0x65, 0x79,
	0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x70, 0x79, 0x77, 0x72, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x63, 0x6f, 0x70, 0x79, 0x77, 0x72,
	0x69, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0xa4, 0x01, 0x0a, 0x13,
	0x43, 0x6f, 0x70, 0x79, 0x77, 0x72, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x4f, 0x6e, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x70, 0x79, 0x77, 0x72, 0x69, 0x74, 0x69,
	0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x63, 0x6f, 0x70,
	0x79, 0x77, 0x72, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x70,
	0x70, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x70, 0x6b,
	0x65, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x2d, 0x0a, 0x12, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x5f, 0x63, 0x6f,
	0x70, 0x79, 0x77, 0x72, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x11, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x43, 0x6f, 0x70, 0x79, 0x77, 0x72, 0x69, 0x74, 0x69,
	0x6e, 0x67, 0x22, 0x73, 0x0a, 0x14, 0x43, 0x6f, 0x70, 0x79, 0x77, 0x72, 0x69, 0x74, 0x69, 0x6e,
	0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x30, 0x0a, 0x04, 0x4c, 0x69,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6f, 0x66, 0x63, 0x2e, 0x61,
	0x70, 0x70, 0x2e, 0x43, 0x6f, 0x70, 0x79, 0x77, 0x72, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x4f, 0x6e,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x08,
	0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x6f, 0x66, 0x63, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x52, 0x08, 0x50,
	0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x22, 0x7a, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x50, 0x61, 0x67, 0x65, 0x74, 0x4e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x50, 0x61, 0x67, 0x65, 0x74, 0x4e, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x67,
	0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x50, 0x61, 0x67,
	0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x50,
	0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x32, 0xf6, 0x05, 0x0a, 0x0d, 0x4f, 0x66, 0x63, 0x41, 0x70, 0x70, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x32, 0x0a, 0x06, 0x41, 0x70, 0x70, 0x41, 0x64, 0x64, 0x12,
	0x13, 0x2e, 0x6f, 0x66, 0x63, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x41, 0x70, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x6f, 0x66, 0x63, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x41,
	0x70, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x07, 0x41, 0x70, 0x70,
	0x53, 0x61, 0x76, 0x65, 0x12, 0x13, 0x2e, 0x6f, 0x66, 0x63, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x41,
	0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x06, 0x4f, 0x6e, 0x65, 0x41, 0x70, 0x70, 0x12, 0x16, 0x2e,
	0x6f, 0x66, 0x63, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x41, 0x70, 0x70, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6f, 0x66, 0x63, 0x2e, 0x61, 0x70, 0x70, 0x2e,
	0x41, 0x70, 0x70, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x3a, 0x0a,
	0x07, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x70, 0x70, 0x12, 0x16, 0x2e, 0x6f, 0x66, 0x63, 0x2e, 0x61,
	0x70, 0x70, 0x2e, 0x41, 0x70, 0x70, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x15, 0x2e, 0x6f, 0x66, 0x63, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x41, 0x70, 0x70, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0a, 0x53, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x53, 0x61, 0x76, 0x65, 0x12, 0x16, 0x2e, 0x6f, 0x66, 0x63, 0x2e, 0x61, 0x70,
	0x70, 0x2e, 0x41, 0x70, 0x70, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x18, 0x2e, 0x6f, 0x66, 0x63, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x0a, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x1a, 0x2e, 0x6f, 0x66, 0x63, 0x2e,
	0x61, 0x70, 0x70, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12,
	0x42, 0x0a, 0x0a, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x1a, 0x2e,
	0x6f, 0x66, 0x63, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x0e, 0x43, 0x6f, 0x70, 0x79, 0x77, 0x72, 0x69, 0x74, 0x69,
	0x6e, 0x67, 0x41, 0x64, 0x64, 0x12, 0x1b, 0x2e, 0x6f, 0x66, 0x63, 0x2e, 0x61, 0x70, 0x70, 0x2e,
	0x43, 0x6f, 0x70, 0x79, 0x77, 0x72, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x0f,
	0x43, 0x6f, 0x70, 0x79, 0x77, 0x72, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x61, 0x76, 0x65, 0x12,
	0x1b, 0x2e, 0x6f, 0x66, 0x63, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x43, 0x6f, 0x70, 0x79, 0x77, 0x72,
	0x69, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x0e, 0x43, 0x6f, 0x70, 0x79, 0x77, 0x72,
	0x69, 0x74, 0x69, 0x6e, 0x67, 0x4f, 0x6e, 0x65, 0x12, 0x1e, 0x2e, 0x6f, 0x66, 0x63, 0x2e, 0x61,
	0x70, 0x70, 0x2e, 0x43, 0x6f, 0x70, 0x79, 0x77, 0x72, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x6f, 0x66, 0x63, 0x2e, 0x61,
	0x70, 0x70, 0x2e, 0x43, 0x6f, 0x70, 0x79, 0x77, 0x72, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x4f, 0x6e,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x0f, 0x43, 0x6f, 0x70, 0x79,
	0x77, 0x72, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1e, 0x2e, 0x6f, 0x66,
	0x63, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x43, 0x6f, 0x70, 0x79, 0x77, 0x72, 0x69, 0x74, 0x69, 0x6e,
	0x67, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x6f, 0x66,
	0x63, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x43, 0x6f, 0x70, 0x79, 0x77, 0x72, 0x69, 0x74, 0x69, 0x6e,
	0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_protobuf_spec_ofc_app_ofc_com_app_proto_rawDescOnce sync.Once
	file_api_protobuf_spec_ofc_app_ofc_com_app_proto_rawDescData = file_api_protobuf_spec_ofc_app_ofc_com_app_proto_rawDesc
)

func file_api_protobuf_spec_ofc_app_ofc_com_app_proto_rawDescGZIP() []byte {
	file_api_protobuf_spec_ofc_app_ofc_com_app_proto_rawDescOnce.Do(func() {
		file_api_protobuf_spec_ofc_app_ofc_com_app_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_protobuf_spec_ofc_app_ofc_com_app_proto_rawDescData)
	})
	return file_api_protobuf_spec_ofc_app_ofc_com_app_proto_rawDescData
}

var file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_protobuf_spec_ofc_app_ofc_com_app_proto_goTypes = []interface{}{
	(*AppRequest)(nil),            // 0: ofc.app.AppRequest
	(*AppReply)(nil),              // 1: ofc.app.AppReply
	(*AppGetRequest)(nil),         // 2: ofc.app.AppGetRequest
	(*AppOneReply)(nil),           // 3: ofc.app.AppOneReply
	(*AppListReply)(nil),          // 4: ofc.app.AppListReply
	(*AppKeyRequest)(nil),         // 5: ofc.app.AppKeyRequest
	(*SecretSaveReply)(nil),       // 6: ofc.app.SecretSaveReply
	(*MessageUrlRequest)(nil),     // 7: ofc.app.MessageUrlRequest
	(*IdentifierRequest)(nil),     // 8: ofc.app.IdentifierRequest
	(*CopywritingRequest)(nil),    // 9: ofc.app.CopywritingRequest
	(*CopywritingGetRequest)(nil), // 10: ofc.app.CopywritingGetRequest
	(*CopywritingOneReply)(nil),   // 11: ofc.app.CopywritingOneReply
	(*CopywritingListReply)(nil),  // 12: ofc.app.CopywritingListReply
	(*Page)(nil),                  // 13: ofc.app.Page
	(*empty.Empty)(nil),           // 14: google.protobuf.Empty
}
var file_api_protobuf_spec_ofc_app_ofc_com_app_proto_depIdxs = []int32{
	3,  // 0: ofc.app.AppListReply.List:type_name -> ofc.app.AppOneReply
	13, // 1: ofc.app.AppListReply.Paginate:type_name -> ofc.app.Page
	11, // 2: ofc.app.CopywritingListReply.List:type_name -> ofc.app.CopywritingOneReply
	13, // 3: ofc.app.CopywritingListReply.Paginate:type_name -> ofc.app.Page
	0,  // 4: ofc.app.OfcAppService.AppAdd:input_type -> ofc.app.AppRequest
	0,  // 5: ofc.app.OfcAppService.AppSave:input_type -> ofc.app.AppRequest
	2,  // 6: ofc.app.OfcAppService.OneApp:input_type -> ofc.app.AppGetRequest
	2,  // 7: ofc.app.OfcAppService.ListApp:input_type -> ofc.app.AppGetRequest
	5,  // 8: ofc.app.OfcAppService.SecretSave:input_type -> ofc.app.AppKeyRequest
	7,  // 9: ofc.app.OfcAppService.MessageUrl:input_type -> ofc.app.MessageUrlRequest
	8,  // 10: ofc.app.OfcAppService.Identifier:input_type -> ofc.app.IdentifierRequest
	9,  // 11: ofc.app.OfcAppService.CopywritingAdd:input_type -> ofc.app.CopywritingRequest
	9,  // 12: ofc.app.OfcAppService.CopywritingSave:input_type -> ofc.app.CopywritingRequest
	10, // 13: ofc.app.OfcAppService.CopywritingOne:input_type -> ofc.app.CopywritingGetRequest
	10, // 14: ofc.app.OfcAppService.CopywritingList:input_type -> ofc.app.CopywritingGetRequest
	1,  // 15: ofc.app.OfcAppService.AppAdd:output_type -> ofc.app.AppReply
	14, // 16: ofc.app.OfcAppService.AppSave:output_type -> google.protobuf.Empty
	3,  // 17: ofc.app.OfcAppService.OneApp:output_type -> ofc.app.AppOneReply
	4,  // 18: ofc.app.OfcAppService.ListApp:output_type -> ofc.app.AppListReply
	6,  // 19: ofc.app.OfcAppService.SecretSave:output_type -> ofc.app.SecretSaveReply
	14, // 20: ofc.app.OfcAppService.MessageUrl:output_type -> google.protobuf.Empty
	14, // 21: ofc.app.OfcAppService.Identifier:output_type -> google.protobuf.Empty
	14, // 22: ofc.app.OfcAppService.CopywritingAdd:output_type -> google.protobuf.Empty
	14, // 23: ofc.app.OfcAppService.CopywritingSave:output_type -> google.protobuf.Empty
	11, // 24: ofc.app.OfcAppService.CopywritingOne:output_type -> ofc.app.CopywritingOneReply
	12, // 25: ofc.app.OfcAppService.CopywritingList:output_type -> ofc.app.CopywritingListReply
	15, // [15:26] is the sub-list for method output_type
	4,  // [4:15] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_protobuf_spec_ofc_app_ofc_com_app_proto_init() }
func file_api_protobuf_spec_ofc_app_ofc_com_app_proto_init() {
	if File_api_protobuf_spec_ofc_app_ofc_com_app_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppOneReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppKeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecretSaveReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdentifierRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CopywritingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CopywritingGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CopywritingOneReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CopywritingListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Page); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_protobuf_spec_ofc_app_ofc_com_app_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_protobuf_spec_ofc_app_ofc_com_app_proto_goTypes,
		DependencyIndexes: file_api_protobuf_spec_ofc_app_ofc_com_app_proto_depIdxs,
		MessageInfos:      file_api_protobuf_spec_ofc_app_ofc_com_app_proto_msgTypes,
	}.Build()
	File_api_protobuf_spec_ofc_app_ofc_com_app_proto = out.File
	file_api_protobuf_spec_ofc_app_ofc_com_app_proto_rawDesc = nil
	file_api_protobuf_spec_ofc_app_ofc_com_app_proto_goTypes = nil
	file_api_protobuf_spec_ofc_app_ofc_com_app_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OfcAppServiceClient is the client API for OfcAppService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OfcAppServiceClient interface {
	AppAdd(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*AppReply, error)
	AppSave(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	OneApp(ctx context.Context, in *AppGetRequest, opts ...grpc.CallOption) (*AppOneReply, error)
	ListApp(ctx context.Context, in *AppGetRequest, opts ...grpc.CallOption) (*AppListReply, error)
	SecretSave(ctx context.Context, in *AppKeyRequest, opts ...grpc.CallOption) (*SecretSaveReply, error)
	MessageUrl(ctx context.Context, in *MessageUrlRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	Identifier(ctx context.Context, in *IdentifierRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	CopywritingAdd(ctx context.Context, in *CopywritingRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	CopywritingSave(ctx context.Context, in *CopywritingRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	CopywritingOne(ctx context.Context, in *CopywritingGetRequest, opts ...grpc.CallOption) (*CopywritingOneReply, error)
	CopywritingList(ctx context.Context, in *CopywritingGetRequest, opts ...grpc.CallOption) (*CopywritingListReply, error)
}

type ofcAppServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOfcAppServiceClient(cc grpc.ClientConnInterface) OfcAppServiceClient {
	return &ofcAppServiceClient{cc}
}

func (c *ofcAppServiceClient) AppAdd(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*AppReply, error) {
	out := new(AppReply)
	err := c.cc.Invoke(ctx, "/ofc.app.OfcAppService/AppAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ofcAppServiceClient) AppSave(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/ofc.app.OfcAppService/AppSave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ofcAppServiceClient) OneApp(ctx context.Context, in *AppGetRequest, opts ...grpc.CallOption) (*AppOneReply, error) {
	out := new(AppOneReply)
	err := c.cc.Invoke(ctx, "/ofc.app.OfcAppService/OneApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ofcAppServiceClient) ListApp(ctx context.Context, in *AppGetRequest, opts ...grpc.CallOption) (*AppListReply, error) {
	out := new(AppListReply)
	err := c.cc.Invoke(ctx, "/ofc.app.OfcAppService/ListApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ofcAppServiceClient) SecretSave(ctx context.Context, in *AppKeyRequest, opts ...grpc.CallOption) (*SecretSaveReply, error) {
	out := new(SecretSaveReply)
	err := c.cc.Invoke(ctx, "/ofc.app.OfcAppService/SecretSave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ofcAppServiceClient) MessageUrl(ctx context.Context, in *MessageUrlRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/ofc.app.OfcAppService/MessageUrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ofcAppServiceClient) Identifier(ctx context.Context, in *IdentifierRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/ofc.app.OfcAppService/Identifier", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ofcAppServiceClient) CopywritingAdd(ctx context.Context, in *CopywritingRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/ofc.app.OfcAppService/CopywritingAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ofcAppServiceClient) CopywritingSave(ctx context.Context, in *CopywritingRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/ofc.app.OfcAppService/CopywritingSave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ofcAppServiceClient) CopywritingOne(ctx context.Context, in *CopywritingGetRequest, opts ...grpc.CallOption) (*CopywritingOneReply, error) {
	out := new(CopywritingOneReply)
	err := c.cc.Invoke(ctx, "/ofc.app.OfcAppService/CopywritingOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ofcAppServiceClient) CopywritingList(ctx context.Context, in *CopywritingGetRequest, opts ...grpc.CallOption) (*CopywritingListReply, error) {
	out := new(CopywritingListReply)
	err := c.cc.Invoke(ctx, "/ofc.app.OfcAppService/CopywritingList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OfcAppServiceServer is the server API for OfcAppService service.
type OfcAppServiceServer interface {
	AppAdd(context.Context, *AppRequest) (*AppReply, error)
	AppSave(context.Context, *AppRequest) (*empty.Empty, error)
	OneApp(context.Context, *AppGetRequest) (*AppOneReply, error)
	ListApp(context.Context, *AppGetRequest) (*AppListReply, error)
	SecretSave(context.Context, *AppKeyRequest) (*SecretSaveReply, error)
	MessageUrl(context.Context, *MessageUrlRequest) (*empty.Empty, error)
	Identifier(context.Context, *IdentifierRequest) (*empty.Empty, error)
	CopywritingAdd(context.Context, *CopywritingRequest) (*empty.Empty, error)
	CopywritingSave(context.Context, *CopywritingRequest) (*empty.Empty, error)
	CopywritingOne(context.Context, *CopywritingGetRequest) (*CopywritingOneReply, error)
	CopywritingList(context.Context, *CopywritingGetRequest) (*CopywritingListReply, error)
}

// UnimplementedOfcAppServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOfcAppServiceServer struct {
}

func (*UnimplementedOfcAppServiceServer) AppAdd(context.Context, *AppRequest) (*AppReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppAdd not implemented")
}
func (*UnimplementedOfcAppServiceServer) AppSave(context.Context, *AppRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppSave not implemented")
}
func (*UnimplementedOfcAppServiceServer) OneApp(context.Context, *AppGetRequest) (*AppOneReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OneApp not implemented")
}
func (*UnimplementedOfcAppServiceServer) ListApp(context.Context, *AppGetRequest) (*AppListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListApp not implemented")
}
func (*UnimplementedOfcAppServiceServer) SecretSave(context.Context, *AppKeyRequest) (*SecretSaveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SecretSave not implemented")
}
func (*UnimplementedOfcAppServiceServer) MessageUrl(context.Context, *MessageUrlRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MessageUrl not implemented")
}
func (*UnimplementedOfcAppServiceServer) Identifier(context.Context, *IdentifierRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Identifier not implemented")
}
func (*UnimplementedOfcAppServiceServer) CopywritingAdd(context.Context, *CopywritingRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CopywritingAdd not implemented")
}
func (*UnimplementedOfcAppServiceServer) CopywritingSave(context.Context, *CopywritingRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CopywritingSave not implemented")
}
func (*UnimplementedOfcAppServiceServer) CopywritingOne(context.Context, *CopywritingGetRequest) (*CopywritingOneReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CopywritingOne not implemented")
}
func (*UnimplementedOfcAppServiceServer) CopywritingList(context.Context, *CopywritingGetRequest) (*CopywritingListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CopywritingList not implemented")
}

func RegisterOfcAppServiceServer(s *grpc.Server, srv OfcAppServiceServer) {
	s.RegisterService(&_OfcAppService_serviceDesc, srv)
}

func _OfcAppService_AppAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfcAppServiceServer).AppAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ofc.app.OfcAppService/AppAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfcAppServiceServer).AppAdd(ctx, req.(*AppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OfcAppService_AppSave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfcAppServiceServer).AppSave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ofc.app.OfcAppService/AppSave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfcAppServiceServer).AppSave(ctx, req.(*AppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OfcAppService_OneApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfcAppServiceServer).OneApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ofc.app.OfcAppService/OneApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfcAppServiceServer).OneApp(ctx, req.(*AppGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OfcAppService_ListApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfcAppServiceServer).ListApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ofc.app.OfcAppService/ListApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfcAppServiceServer).ListApp(ctx, req.(*AppGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OfcAppService_SecretSave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfcAppServiceServer).SecretSave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ofc.app.OfcAppService/SecretSave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfcAppServiceServer).SecretSave(ctx, req.(*AppKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OfcAppService_MessageUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfcAppServiceServer).MessageUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ofc.app.OfcAppService/MessageUrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfcAppServiceServer).MessageUrl(ctx, req.(*MessageUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OfcAppService_Identifier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdentifierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfcAppServiceServer).Identifier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ofc.app.OfcAppService/Identifier",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfcAppServiceServer).Identifier(ctx, req.(*IdentifierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OfcAppService_CopywritingAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopywritingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfcAppServiceServer).CopywritingAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ofc.app.OfcAppService/CopywritingAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfcAppServiceServer).CopywritingAdd(ctx, req.(*CopywritingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OfcAppService_CopywritingSave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopywritingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfcAppServiceServer).CopywritingSave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ofc.app.OfcAppService/CopywritingSave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfcAppServiceServer).CopywritingSave(ctx, req.(*CopywritingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OfcAppService_CopywritingOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopywritingGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfcAppServiceServer).CopywritingOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ofc.app.OfcAppService/CopywritingOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfcAppServiceServer).CopywritingOne(ctx, req.(*CopywritingGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OfcAppService_CopywritingList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopywritingGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfcAppServiceServer).CopywritingList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ofc.app.OfcAppService/CopywritingList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfcAppServiceServer).CopywritingList(ctx, req.(*CopywritingGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OfcAppService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ofc.app.OfcAppService",
	HandlerType: (*OfcAppServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AppAdd",
			Handler:    _OfcAppService_AppAdd_Handler,
		},
		{
			MethodName: "AppSave",
			Handler:    _OfcAppService_AppSave_Handler,
		},
		{
			MethodName: "OneApp",
			Handler:    _OfcAppService_OneApp_Handler,
		},
		{
			MethodName: "ListApp",
			Handler:    _OfcAppService_ListApp_Handler,
		},
		{
			MethodName: "SecretSave",
			Handler:    _OfcAppService_SecretSave_Handler,
		},
		{
			MethodName: "MessageUrl",
			Handler:    _OfcAppService_MessageUrl_Handler,
		},
		{
			MethodName: "Identifier",
			Handler:    _OfcAppService_Identifier_Handler,
		},
		{
			MethodName: "CopywritingAdd",
			Handler:    _OfcAppService_CopywritingAdd_Handler,
		},
		{
			MethodName: "CopywritingSave",
			Handler:    _OfcAppService_CopywritingSave_Handler,
		},
		{
			MethodName: "CopywritingOne",
			Handler:    _OfcAppService_CopywritingOne_Handler,
		},
		{
			MethodName: "CopywritingList",
			Handler:    _OfcAppService_CopywritingList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/protobuf-spec/ofc_app/ofc_com_app.proto",
}
