// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: api/protobuf-spec/ofc_im_user/ofc_im_user.proto

package ofc_im_user

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ImUserRegisterStatistics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: v:"required|#企业账户不能为空"
	Cid       string `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty" v:"required#企业账户不能为空"`
	StartTime string `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   string `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Appkey    string `protobuf:"bytes,4,opt,name=appkey,proto3" json:"appkey,omitempty"`
}

func (x *ImUserRegisterStatistics) Reset() {
	*x = ImUserRegisterStatistics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_ofc_im_user_ofc_im_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImUserRegisterStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImUserRegisterStatistics) ProtoMessage() {}

func (x *ImUserRegisterStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_ofc_im_user_ofc_im_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImUserRegisterStatistics.ProtoReflect.Descriptor instead.
func (*ImUserRegisterStatistics) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_ofc_im_user_ofc_im_user_proto_rawDescGZIP(), []int{0}
}

func (x *ImUserRegisterStatistics) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *ImUserRegisterStatistics) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *ImUserRegisterStatistics) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *ImUserRegisterStatistics) GetAppkey() string {
	if x != nil {
		return x.Appkey
	}
	return ""
}

type StatisticsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*StatisticsReply_List `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *StatisticsReply) Reset() {
	*x = StatisticsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_ofc_im_user_ofc_im_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatisticsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsReply) ProtoMessage() {}

func (x *StatisticsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_ofc_im_user_ofc_im_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsReply.ProtoReflect.Descriptor instead.
func (*StatisticsReply) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_ofc_im_user_ofc_im_user_proto_rawDescGZIP(), []int{1}
}

func (x *StatisticsReply) GetList() []*StatisticsReply_List {
	if x != nil {
		return x.List
	}
	return nil
}

type StatisticsReply_List struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date  string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Count int64  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *StatisticsReply_List) Reset() {
	*x = StatisticsReply_List{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_spec_ofc_im_user_ofc_im_user_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatisticsReply_List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticsReply_List) ProtoMessage() {}

func (x *StatisticsReply_List) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_spec_ofc_im_user_ofc_im_user_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticsReply_List.ProtoReflect.Descriptor instead.
func (*StatisticsReply_List) Descriptor() ([]byte, []int) {
	return file_api_protobuf_spec_ofc_im_user_ofc_im_user_proto_rawDescGZIP(), []int{1, 0}
}

func (x *StatisticsReply_List) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *StatisticsReply_List) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_api_protobuf_spec_ofc_im_user_ofc_im_user_proto protoreflect.FileDescriptor

var file_api_protobuf_spec_ofc_im_user_ofc_im_user_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2d, 0x73,
	0x70, 0x65, 0x63, 0x2f, 0x6f, 0x66, 0x63, 0x5f, 0x69, 0x6d, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x2f,
	0x6f, 0x66, 0x63, 0x5f, 0x69, 0x6d, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0b, 0x6f, 0x66, 0x63, 0x2e, 0x69, 0x6d, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x1a, 0x36,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x77, 0x69, 0x74, 0x6b,
	0x6f, 0x77, 0x2f, 0x67, 0x6f, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x96, 0x01, 0x0a, 0x18, 0x49, 0x6d, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74,
	0x69, 0x63, 0x73, 0x12, 0x18, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x06, 0xe2, 0xdf, 0x1f, 0x02, 0x58, 0x01, 0x52, 0x03, 0x63, 0x69, 0x64, 0x12, 0x25, 0x0a,
	0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x42, 0x06, 0xe2, 0xdf, 0x1f, 0x02, 0x58, 0x01, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x06, 0xe2, 0xdf, 0x1f, 0x02, 0x58, 0x01, 0x52, 0x07,
	0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x6b, 0x65,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x70, 0x70, 0x6b, 0x65, 0x79, 0x22,
	0x7a, 0x0a, 0x0f, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x35, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x21, 0x2e, 0x6f, 0x66, 0x63, 0x2e, 0x69, 0x6d, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x1a, 0x30, 0x0a, 0x04, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0x67, 0x0a, 0x10, 0x49,
	0x6d, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x12,
	0x53, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x55, 0x73, 0x65, 0x72, 0x12, 0x25, 0x2e,
	0x6f, 0x66, 0x63, 0x2e, 0x69, 0x6d, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x49, 0x6d, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73,
	0x74, 0x69, 0x63, 0x73, 0x1a, 0x1c, 0x2e, 0x6f, 0x66, 0x63, 0x2e, 0x69, 0x6d, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_protobuf_spec_ofc_im_user_ofc_im_user_proto_rawDescOnce sync.Once
	file_api_protobuf_spec_ofc_im_user_ofc_im_user_proto_rawDescData = file_api_protobuf_spec_ofc_im_user_ofc_im_user_proto_rawDesc
)

func file_api_protobuf_spec_ofc_im_user_ofc_im_user_proto_rawDescGZIP() []byte {
	file_api_protobuf_spec_ofc_im_user_ofc_im_user_proto_rawDescOnce.Do(func() {
		file_api_protobuf_spec_ofc_im_user_ofc_im_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_protobuf_spec_ofc_im_user_ofc_im_user_proto_rawDescData)
	})
	return file_api_protobuf_spec_ofc_im_user_ofc_im_user_proto_rawDescData
}

var file_api_protobuf_spec_ofc_im_user_ofc_im_user_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_protobuf_spec_ofc_im_user_ofc_im_user_proto_goTypes = []interface{}{
	(*ImUserRegisterStatistics)(nil), // 0: ofc.im.user.ImUserRegisterStatistics
	(*StatisticsReply)(nil),          // 1: ofc.im.user.StatisticsReply
	(*StatisticsReply_List)(nil),     // 2: ofc.im.user.StatisticsReply.List
}
var file_api_protobuf_spec_ofc_im_user_ofc_im_user_proto_depIdxs = []int32{
	2, // 0: ofc.im.user.StatisticsReply.list:type_name -> ofc.im.user.StatisticsReply.List
	0, // 1: ofc.im.user.ImUserStatistics.StatisUser:input_type -> ofc.im.user.ImUserRegisterStatistics
	1, // 2: ofc.im.user.ImUserStatistics.StatisUser:output_type -> ofc.im.user.StatisticsReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_protobuf_spec_ofc_im_user_ofc_im_user_proto_init() }
func file_api_protobuf_spec_ofc_im_user_ofc_im_user_proto_init() {
	if File_api_protobuf_spec_ofc_im_user_ofc_im_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_protobuf_spec_ofc_im_user_ofc_im_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImUserRegisterStatistics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_ofc_im_user_ofc_im_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatisticsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_spec_ofc_im_user_ofc_im_user_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatisticsReply_List); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_protobuf_spec_ofc_im_user_ofc_im_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_protobuf_spec_ofc_im_user_ofc_im_user_proto_goTypes,
		DependencyIndexes: file_api_protobuf_spec_ofc_im_user_ofc_im_user_proto_depIdxs,
		MessageInfos:      file_api_protobuf_spec_ofc_im_user_ofc_im_user_proto_msgTypes,
	}.Build()
	File_api_protobuf_spec_ofc_im_user_ofc_im_user_proto = out.File
	file_api_protobuf_spec_ofc_im_user_ofc_im_user_proto_rawDesc = nil
	file_api_protobuf_spec_ofc_im_user_ofc_im_user_proto_goTypes = nil
	file_api_protobuf_spec_ofc_im_user_ofc_im_user_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ImUserStatisticsClient is the client API for ImUserStatistics service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ImUserStatisticsClient interface {
	StatisUser(ctx context.Context, in *ImUserRegisterStatistics, opts ...grpc.CallOption) (*StatisticsReply, error)
}

type imUserStatisticsClient struct {
	cc grpc.ClientConnInterface
}

func NewImUserStatisticsClient(cc grpc.ClientConnInterface) ImUserStatisticsClient {
	return &imUserStatisticsClient{cc}
}

func (c *imUserStatisticsClient) StatisUser(ctx context.Context, in *ImUserRegisterStatistics, opts ...grpc.CallOption) (*StatisticsReply, error) {
	out := new(StatisticsReply)
	err := c.cc.Invoke(ctx, "/ofc.im.user.ImUserStatistics/StatisUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImUserStatisticsServer is the server API for ImUserStatistics service.
type ImUserStatisticsServer interface {
	StatisUser(context.Context, *ImUserRegisterStatistics) (*StatisticsReply, error)
}

// UnimplementedImUserStatisticsServer can be embedded to have forward compatible implementations.
type UnimplementedImUserStatisticsServer struct {
}

func (*UnimplementedImUserStatisticsServer) StatisUser(context.Context, *ImUserRegisterStatistics) (*StatisticsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StatisUser not implemented")
}

func RegisterImUserStatisticsServer(s *grpc.Server, srv ImUserStatisticsServer) {
	s.RegisterService(&_ImUserStatistics_serviceDesc, srv)
}

func _ImUserStatistics_StatisUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImUserRegisterStatistics)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImUserStatisticsServer).StatisUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ofc.im.user.ImUserStatistics/StatisUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImUserStatisticsServer).StatisUser(ctx, req.(*ImUserRegisterStatistics))
	}
	return interceptor(ctx, in, info, handler)
}

var _ImUserStatistics_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ofc.im.user.ImUserStatistics",
	HandlerType: (*ImUserStatisticsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StatisUser",
			Handler:    _ImUserStatistics_StatisUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/protobuf-spec/ofc_im_user/ofc_im_user.proto",
}
